### ISSUE TITLE
Publish the 1.3.4 version

### ISSUE THREAD

**Issue by oscarotero** [kartik-v/php-date-formatter#13]
Hi, I'd like to use the version 1.3.4 that includes the fix for #11 but it's not available in bower.
Can you release this version, please?
Thanks!

**Comment by rogyw** [comment]
+1 Please tag with 1.3.4 and update the latest release when possible for bower use. Thanks.

**Comment by anikgoel** [comment]
@kartik-v

How can I use this plugin using npm.

After successful installation. I used
const phpDateFormatter = require('php-date-formatter');

But phpDateFormatter do not come with any plugin data.
Can you help me on this?

Thanks :)
