### ISSUE TITLE
parseDate with format Ymd (no separator)

### ISSUE THREAD

**Issue by gillesvrstrtn** [kartik-v/php-date-formatter#17]
Hi, 
I can't manage to correctly parse a date with Ymd format (without any separator), for example I would like 20150328 to be parsed as March 28, 2015.

When I do something like fmt.parseDate("20150328", "Ymd"), I get a false instead of a Date object.

Could you please tell me how I can parse this string correctly to a Date with the Ymd without any separator in between year, month and day?

Thanks.

**Comment by kartik-v** [comment]
This is out of scope of `parseDate` - which relies specifically on separators to correctly identify each date part in the format string. Before you use `parseDate`, you may want to convert your source data to a format with separators and pass it to the JS function parse date to be effective - note that you can use any separator character that is defined via the `separators` property of the library which by default supports the space character (` `), colon (`:`), hyphen (`-`), plus (`+`), forward slash (`/`) and period (`.`)
