### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by sbrunner** [kartik-v/php-date-formatter#18]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of php-date-formatter.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/php-date-formatter) and [demos](http://plugins.krajee.com/php-date-formatter/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## ES6 Modules

Is it possible to make it available throw ES6 modules, actually it's difficult to integrate it in webpack ...

**Comment by ericmorand** [comment]
Yes, what is the point of having this lib available on npm if it is *not* usable with NodeJS?

**Comment by sbrunner** [comment]
... To use it with Webpack or an other tools like it ...

**Comment by kartik-v** [comment]
Can you please submit a PR? Open for an enhancement

**Comment by sbrunner** [comment]
Yes, I will work on that :-)

**Comment by ericmorand** [comment]
@sbrunner

> ... To use it with Webpack or an other tools like it ...

I don't get it. How do you import it in a webpack module? Correct me if I'm wrong but this lib is not exporting anything.

**Comment by kartik-v** [comment]
Hi folks let me take a stab at this for providing Universal module support via AMD, npm, and browser globals

**Comment by sbrunner** [comment]
Universal module support via AMD ?
Universal module is ES6 modules since ECMAScript version 6 (alias 2015) is released (in June 2015)...
