### ISSUE TITLE
Format h:iA (no space before the 'A') results in 7:00PM output as 7:00AM

### ISSUE THREAD

**Issue by bjacobs** [kartik-v/php-date-formatter#21]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of php-date-formatter.
- [x ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/php-date-formatter) and [demos](http://plugins.krajee.com/php-date-formatter/demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Send a time with format vFormat='h:iA' and vDate='7:00PM'
Note that there is no space between 'i' and 'A'.
In parseDate there is an assumption that there will be a valid separator between 'A' and other format parts. 

vMeriIndex finds 'A' as index 2 in the vFormatParts array, but vDateParts won't have a third entry.
mer = vDateParts[vMeriIndex];

I think it would be beneficial if the plugin could handle this format, although I'm pretty sure having the space is the standard. Or perhaps if it could return an error.

This came to my attention when using datetimepicker as a timepicker with format h:iA

2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
The value returned corresponds to 7:00AM instead of PM

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- php-date-formatter version: 1.3.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/php-date-formatter/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using php-date-formatter without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Yes you need the separator to isolate and detect format patterns and format correctly  (e.g.space,  comma,  colon or hyphen)
