### ISSUE TITLE
Cannot parse Tuesday or Thursday dates using "D, j M Y" format

### ISSUE THREAD

**Issue by ikaronen-relex** [kartik-v/php-date-formatter#24]
## Steps to reproduce the issue

1. Go to https://plugins.krajee.com/php-date-formatter/demo.
2. Enter `D, j M Y` as the input format.
3. Enter a date that falls on a Tuesday or Thurdays, such as `Thu, 5 Dec 2019`.

## Expected behavior and actual behavior

* Expected: parsing succeeds.
* Observed: parsing fails with "Error: Cannot parse source date".

Further experimentation points to the trigger being the initial `T` in the input string.  In particular, all of the following fail to parse:

* `Tue, 3 Dec 2019`
* `Thu, 5 Dec 2019`
* `Thu, 6 Dec 2019`
* `Test, 6 Dec 2019`
* `T, 6 Dec 2019`

whereas all of the following are accepted:

* `Wed, 4 Dec 2019`
* `Fri, 6 Dec 2019`
* `Wed, 5 Dec 2019` (parsed as Thursday the 5th)
* `Whatever, 5 Dec 2019` (also parsed as Thursday the 5th)
* `X, 5 Dec 2019` (ditto)

## Environment

Browsers

- [X] Google Chrome 78.0
- [X] Mozilla Firefox 71.0
- [X] Safari 13.0.3

Operating System

- [X] Mac OS X

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/php-date-formatter/demo)
- [X] The bug happens consistently across all tested browsers

**Comment by ikaronen-relex** [comment]
Hi, stalebot. Nice to see that somebody noticed this bug report, even if you're just a bot. I guess the lack of a non-bot response means this project is no longer being maintained, then?

**Comment by kartik-v** [comment]
@ikaronen-relex thanks for the report... Will need to check this... Feel free to update any suggestion... Have not got time to look into this... Will try to check on this soon

**Comment by kartik-v** [comment]
Resolved via above commit.
