### ISSUE TITLE
Node package ownership

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/php-date-formatter#25]
Request @haremo to transfer package ownership for php-date-formatter to @kartik-v on npm [using these instructions](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)

**Comment by kartik-v** [comment]
Request @haremo to transfer package ownership for php-date-formatter to @kartik-v on npm [using these instructions](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)

**Comment by Alonski** [comment]
@kartik-v So you can't release yet?

**Comment by kartik-v** [comment]
Hi @Alonski correct. I cannot push this release through node - because @haremo had pushed the earlier release.

**Comment by Alonski** [comment]
Hmm if he's unavailable maybe you can contact NPM?

**Comment by kartik-v** [comment]
This is done thanks.
